language: java

jdk:
  - oraclejdk10
env:
  secure: "rNrH/Un9b8yo1/7oGAssltM4jasRLAG4t983hUdDyj73jWobO+Pd48NE7etuVhuFhNUUv1qdyo0B+XGd6F5AbH5kBoapfG+fG4cChQh2kTPZVRSGlnAcDwbFEVpVkU2AXhwljaA+rcngX1tTxBhWthQB1pm7B8wu29o5UhKtF6N8QdaAcPHqRcZzADXCn39s+gu9C1Xwg3b8hMPDRMhlQnVeU2guk+HXF+DSQWcTJ+ZmdVhk/XVv2yEMckVH6BkSPb+FUgZtW1hMMTAlXTP352eF6VJv79Fsl86qFmKuy5EeAolFKDcEdClMxDLJZ4tclcyNmWO2AGQBk3yv3wV1Eo6j9FDE8SND6j3xXNAS57xp0sKMCdkVRRdjYJ2hZ7AlVty4lJLTD4omibzeRdkpgo97Z3na+xIs1100oyQY3BmZqALk40RnUJujHVrhD7YDBLVOVpScDIB5p6Udn7R678FTfT5sCrwO6WmLIrTIyJveTqFFyH/b4e2n+ypnE+hDogahDhyrRptdBNwXV5gS9IdMR8R577tmyYmRhbtaG2DbMLVaQjFWCjpU/Ea8ckaOGn3s5R7MGOzF5aOVDUOHWswXBxf+dFaCJDkkNuUEfhaBryr7WZU12rI6iptYFBdDjV/CVHITV65GNCTleE+E7G4JKPuAe/Wbx17zh4cWksI="

after_success:
  - ./gradlew cobertura coveralls